title: Philippe Louis Jr
#logo: 
description: Aspiring Data Scientist & Machine Learning Engineer | Educator | Passionate About Data-Driven Solutions | Data Science Master's Student @ Syracuse University School of Information Studies
#show_downloads: true
theme: jekyll-theme-midnight
